1. Create a function generate_temperature that accepts a min and max range, and then number of temperatures count that need to be created. This function must return a list with count temperatures.

In [1]:
import random

def generate_temperature(min, max, count):
    return [random.randint(min, max) for _ in range(count)]

2. Create a numpy array temperature_data that has 7-day temperature readings for 5 cities. Limit the temperature to be between 15 and 35.

In [2]:
import numpy as np

temperature_data = np.array([generate_temperature(15, 35, 7) for _ in range(5)])
print(temperature_data)

[[25 27 32 32 19 32 25]
 [22 29 35 31 20 17 26]
 [19 26 32 33 23 30 30]
 [31 33 34 27 26 17 30]
 [24 28 25 18 26 19 26]]


3. Print the shape of temperature_data to ensure its (5,7).

In [3]:
print(temperature_data.shape)

(5, 7)


4. Display the overall average_temperature.

In [4]:
print(np.mean(temperature_data))

26.542857142857144


5. Display the average temperature per city.

In [5]:
print(np.mean(temperature_data, axis=1))

[27.42857143 25.71428571 27.57142857 28.28571429 23.71428571]


6. Extract the temperature data for the first 3 days of City B, and print them.

In [6]:
city_b_first_3 = temperature_data[1, :3]
print(city_b_first_3)

[22 29 35]


7. Create a new numpy array temperature_f that has all the values covnerted to fahrenheit. Display the overall average temperature in F.

In [7]:
temperature_f = (temperature_data * 9/5)+32
print(temperature_f.mean())

79.77714285714286


8. Find the day with the highest temperature for City D. Display the day number, and the relative temperature.

In [9]:
day = np.argmax(temperature_data[3])+1
print (f"Day {day} is the highest temperature of {temperature_data[3][day-1]} in the City D")

Day 3 is the highest temperature of 34 in the City D


9. Create a new numpy array all_temps with a 1D array of all temperatures.

In [10]:
all_temps = temperature_data.reshape(-1)

10. For each city, calculate the temperature difference between the highest and the lowest temperatures. Then, display the highest fluctuation.

In [13]:
temp_differences = np.max(temperature_data, axis=1) - np.min(temperature_data, axis=1)
print(f'The differences are: {temp_differences}')
print(f'Highest fluctuation: {np.max(temp_differences)}')

The differences are: [13 18 14 17 10]
Highest fluctuation: 18


11. Generate a numpy array weights that has 7 values evenly spread out from 0 to 1. Then multiply these weights with the temperatures.

In [14]:
weights = np.linspace(0, 1, 7)
weighted_temps =temperature_data * weights

print(weighted_temps)

[[ 0.          4.5        10.66666667 16.         12.66666667 26.66666667
  25.        ]
 [ 0.          4.83333333 11.66666667 15.5        13.33333333 14.16666667
  26.        ]
 [ 0.          4.33333333 10.66666667 16.5        15.33333333 25.
  30.        ]
 [ 0.          5.5        11.33333333 13.5        17.33333333 14.16666667
  30.        ]
 [ 0.          4.66666667  8.33333333  9.         17.33333333 15.83333333
  26.        ]]


12. Given a heat index of [1.1, 1.2, 1.1, 1.3, 1.2, 1.1, 1.2], display the total heat index for each city.

In [15]:
heat_index_modifier = np.array([1.1, 1.2, 1.1, 1.3, 1.2, 1.1, 1.2])
total_heat_index = np.dot(temperature_data, heat_index_modifier)
print("Total heat index for each city:", total_heat_index)

Total heat index for each city: [224.7 211.7 226.8 232.1 194.2]
